name: Deploy Astro to Vercel

on:
  push:
    branches: [workflows]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Debug - List directory structure and file contents
        run: |
          echo "Current directory structure:"
          ls -R src
          echo "Content of RoadmapCardList.astro:"
          cat src/components/RoadmapCardList.astro
          echo "Content of [roadmapId]/index.astro:"
          cat src/pages/[roadmapId]/index.astro
          echo "Content of modalStore file (if exists):"
          cat src/stores/modalStore.ts || echo "modalStore.ts not found"
          cat src/stores/modalStore.js || echo "modalStore.js not found"

      - name: Build project
        run: pnpm build

      - name: Deploy to Vercel
        if: github.event_name != 'pull_request'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes