name: Deploy Astro to Vercel

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          
      - name: Clear Git cache and reset
        run: |
          git rm -rf --cached .
          git reset --hard

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: List directory contents
        run: |
          echo "Contents of src/components:"
          ls -la src/components/

      - name: Build project
        run: pnpm build

      - name: Deploy to Vercel
        if: github.event_name != 'pull_request'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes